'use client';

import * as React from 'react';
import { PlusCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Customer } from '@/types/customer';
import { CustomerDataTable } from '@/components/customer/customer-data-table';
import { columns as customerColumns } from '@/components/customer/customer-table-columns';
import CustomerFormDialog from '@/components/customer/customer-form-dialog'; // Will create this next

// Mock data for now
const initialCustomers: Customer[] = [
  {
    id: 'cust_1',
    name: 'Andi Budiman',
    address: 'Jl. Merdeka No. 10, Jakarta',
    phoneNumber: '081234567890',
    email: 'andi.b@example.com',
    wifiPackage: '20 Mbps',
    joinDate: new Date('2023-01-15').toISOString(),
    installationDate: new Date('2023-01-17').toISOString(),
    billingCycleDay: 15,
    status: 'aktif',
    paymentHistory: [],
    notes: 'Pelanggan lama, pembayaran selalu tepat waktu.',
  },
  {
    id: 'cust_2',
    name: 'Siti Aminah',
    address: 'Jl. Pahlawan No. 5, Bandung',
    phoneNumber: '085678901234',
    email: 'siti.a@example.com',
    wifiPackage: '10 Mbps',
    joinDate: new Date('2023-03-20').toISOString(),
    billingCycleDay: 20,
    status: 'isolir',
    paymentHistory: [],
    notes: 'Sering telat bayar.',
  },
  {
    id: 'cust_3',
    name: 'Budi Santoso',
    address: 'Jl. Kebangsaan No. 1, Surabaya',
    phoneNumber: '087812345678',
    wifiPackage: '50 Mbps',
    joinDate: new Date('2024-01-10').toISOString(),
    billingCycleDay: 10,
    status: 'baru',
    paymentHistory: [],
  },
];

export default function AdminPelangganPage() {
  const [customers, setCustomers] = React.useState<Customer[]>(initialCustomers);
  const [isFormOpen, setIsFormOpen] = React.useState(false);
  const [editingCustomer, setEditingCustomer] = React.useState<Customer | null>(null);

  const handleAddCustomer = () => {
    setEditingCustomer(null);
    setIsFormOpen(true);
  };

  const handleEditCustomer = (customer: Customer) => {
    setEditingCustomer(customer);
    setIsFormOpen(true);
  };

  const handleDeleteCustomer = (customerId: string) => {
    // Add confirmation dialog here in a real app
    setCustomers(customers.filter((c) => c.id !== customerId));
  };

  const handleSaveCustomer = (customerData: Omit<Customer, 'id' | 'paymentHistory'> | Customer) => {
    if ('id' in customerData) {
      // Editing existing customer
      setCustomers(customers.map((c) => (c.id === customerData.id ? { ...c, ...customerData } : c)));
    } else {
      // Adding new customer
      // In a real app, ID would be generated by the backend or a robust UUID library
      const newId = `cust_${Math.random().toString(36).substr(2, 9)}`;
      setCustomers([...customers, { ...customerData, id: newId, paymentHistory: [] }]);
    }
    setIsFormOpen(false);
    setEditingCustomer(null);
  };
  
  // Pass edit and delete handlers to columns definition
  const columns = customerColumns({ onEdit: handleEditCustomer, onDelete: handleDeleteCustomer });

  return (
    <div className="container mx-auto py-2">
      <div className="flex items-center justify-between mb-6">
        {/* Title is handled by AdminLayout */}
      </div>

      <div className="bg-card p-6 rounded-lg shadow">
        <div className="flex justify-end mb-4">
          <Button onClick={handleAddCustomer}>
            <PlusCircle className="mr-2 h-4 w-4" /> Tambah Pelanggan
          </Button>
        </div>
        <CustomerDataTable columns={columns} data={customers} />
      </div>

      <CustomerFormDialog
        isOpen={isFormOpen}
        onClose={() => {
          setIsFormOpen(false);
          setEditingCustomer(null);
        }}
        onSubmit={handleSaveCustomer}
        customerToEdit={editingCustomer}
      />
    </div>
  );
}
